### ISSUE TITLE
Support coffeelint 1.8.1

### ISSUE THREAD

**Issue by karlhorky** [levibuzolic/coffeelint-advanced-colon-assignment-spacing#2]
Can this module be updated to support the new version of coffeelint (`1.8.1`)? 

[I tried](https://github.com/karlhorky/coffeelint-advanced-colon-assignment-spacing/commit/58c4b70b73c2468a1dc89b57a24016412c49810e) updating the `peerDependencies` entry but it gave me a generic error:

```
Error loading advanced_colon_assignment_spacing
```

**Comment by levibuzolic** [comment]
Should be resolved in #3.

Cutting a new release now.

**Comment by karlhorky** [comment]
Thanks!
